version: '3.8'

services:
  inventory-app:
    build: .
    container_name: inventory-forecast-app
    ports:
      - "7342:7342"  # Updated port to match README
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

