version: '3.8'

services:
  inventory-app:
    image: python:3.11-slim
    container_name: inventory-forecast-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    command: >
      sh -c "pip install --upgrade pip && \
             pip install -r requirements.txt && \
             streamlit run inventory_forecast.py --server.port 8501 --server.address 0.0.0.0"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
